HOST: http://siren-alps.herokuapp.com

--- ALPS Microblog API in Siren ---
---
This is a Siren example implementationof the ALPS spec.
---

--
Home
This is the home resource.
--

GET /
< 200
< Content-Type: application/vnd.siren+json
{
  "entities": [
    {
      "href": "...",
      "rel": [
        "messages-all"
      ]
    },
    {
      "href": "...",
      "rel": [
        "users-all"
      ]
    }
  ],
  "actions": [
    {
      "name": "message-post",
      "href": "...",
      "method": "POST",
      "fields": [
        {
          "name": "message",
          "type": "text"
        }
      ]
    },
    {
      "name": "user-add",
      "href": "...",
      "method": "POST",
      "fields": [
        {
          "name": "user",
          "type": "text"
        },
        {
          "name": "email",
          "type": "text"
        },
        {
          "name": "password",
          "type": "password"
        }
      ]
    }
  ],
  "links": [
    {
      "rel": [
        "self",
        "index"
      ],
      "href": "..."
    }
  ]
}

--
Messages
This is the messages resource.
--
GET /messages
< 200
< Content-Type: application/vnd.siren+json
{
  "class": [
    "all",
    "messages"
  ],
  "entities": [
    {
      "class": [
        "message"
      ],
      "properties": {
        "user-text": "lee",
        "message-text": "just getting started",
        "date-time": "2011-06-20"
      },
      "entities": [
        {
          "href": "...",
          "rel": [
            "user"
          ]
        },
        {
          "href": "...",
          "rel": [
            "message"
          ]
        }
      ]
    }
  ],
  "actions": [
    {
      "name": "message-post",
      "href": "...",
      "method": "POST",
      "fields": [
        {
          "name": "message",
          "type": "text"
        }
      ]
    }
  ],
  "links": [
    {
      "rel": [
        "self",
        "messages-all"
      ],
      "href": "..."
    },
    {
      "rel": [
        "index"
      ],
      "href": "..."
    }
  ]
}